### ISSUE TITLE
Request to use on shirts for Sydney PM

### ISSUE THREAD

**Issue by djzort** [kraih/perl-raptor#2]
Hi Kraih

We would like to use your raptor logo on shirts for Sydney PM, however the license requires attribution which is difficult on a shirt.

Could you please permit us to have printed and sell shirts for Sydney PM using your design?

Please note that small profit from sales will be used to provide shirts for speakers and pay for some costs relating to promoting Sydney PM (principally meetup.com but also FB ads)

Dean

**Comment by kraih** [comment]
Sorry, i somehow missed this request at the time.
